[package]
name = "unottr-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "unottr"
path = "src/main.rs"

[dependencies]
unottr-core.workspace = true
anyhow.workspace = true
serde_json.workspace = true
tracing.workspace = true
clap = { version = "4.6.6", features = ["derive"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
ctrlc = "3.5.2"
